# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conf.ui'
#
# Created: Sat Sep 19 17:50:40 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(963, 722)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(158, 158, 158);\n"
"color: rgb(0, 0, 0);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tableView_Schedule = QtGui.QTableView(self.centralwidget)
        self.tableView_Schedule.setGeometry(QtCore.QRect(10, 130, 931, 241))
        self.tableView_Schedule.setObjectName(_fromUtf8("tableView_Schedule"))
        self.frame_Control = QtGui.QFrame(self.centralwidget)
        self.frame_Control.setGeometry(QtCore.QRect(390, 370, 551, 311))
        self.frame_Control.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Control.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Control.setObjectName(_fromUtf8("frame_Control"))
        self.toolButton_Stop = QtGui.QToolButton(self.frame_Control)
        self.toolButton_Stop.setGeometry(QtCore.QRect(396, 220, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButton_Stop.setFont(font)
        self.toolButton_Stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_Stop.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 4);"))
        self.toolButton_Stop.setObjectName(_fromUtf8("toolButton_Stop"))
        self.toolButton_Start = QtGui.QToolButton(self.frame_Control)
        self.toolButton_Start.setGeometry(QtCore.QRect(474, 220, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.toolButton_Start.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButton_Start.setFont(font)
        self.toolButton_Start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_Start.setAutoFillBackground(False)
        self.toolButton_Start.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.toolButton_Start.setObjectName(_fromUtf8("toolButton_Start"))
        self.frame_Communication = QtGui.QFrame(self.frame_Control)
        self.frame_Communication.setGeometry(QtCore.QRect(410, 120, 120, 80))
        self.frame_Communication.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Communication.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Communication.setObjectName(_fromUtf8("frame_Communication"))
        self.checkBox_Telescope = QtGui.QCheckBox(self.frame_Communication)
        self.checkBox_Telescope.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.checkBox_Telescope.setChecked(True)
        self.checkBox_Telescope.setObjectName(_fromUtf8("checkBox_Telescope"))
        self.checkBox_Backend = QtGui.QCheckBox(self.frame_Communication)
        self.checkBox_Backend.setGeometry(QtCore.QRect(10, 50, 85, 20))
        self.checkBox_Backend.setChecked(True)
        self.checkBox_Backend.setObjectName(_fromUtf8("checkBox_Backend"))
        self.label_Communication = QtGui.QLabel(self.frame_Control)
        self.label_Communication.setGeometry(QtCore.QRect(420, 110, 97, 16))
        self.label_Communication.setObjectName(_fromUtf8("label_Communication"))
        self.frame_Manual = QtGui.QFrame(self.frame_Control)
        self.frame_Manual.setEnabled(True)
        self.frame_Manual.setGeometry(QtCore.QRect(10, 104, 381, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 224, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 224, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 224, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 224, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 224, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 224, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 224, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 224, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 224, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_Manual.setPalette(palette)
        self.frame_Manual.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_Manual.setStyleSheet(_fromUtf8("background-color: rgb(176, 224, 230);\n"
""))
        self.frame_Manual.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Manual.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Manual.setObjectName(_fromUtf8("frame_Manual"))
        self.label_Mannual = QtGui.QLabel(self.frame_Manual)
        self.label_Mannual.setGeometry(QtCore.QRect(150, 0, 51, 21))
        self.label_Mannual.setObjectName(_fromUtf8("label_Mannual"))
        self.label_Man_RA = QtGui.QLabel(self.frame_Manual)
        self.label_Man_RA.setGeometry(QtCore.QRect(10, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Man_RA.setFont(font)
        self.label_Man_RA.setObjectName(_fromUtf8("label_Man_RA"))
        self.label_Man_DEC = QtGui.QLabel(self.frame_Manual)
        self.label_Man_DEC.setGeometry(QtCore.QRect(10, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Man_DEC.setFont(font)
        self.label_Man_DEC.setObjectName(_fromUtf8("label_Man_DEC"))
        self.textEdit_RAset = QtGui.QTextEdit(self.frame_Manual)
        self.textEdit_RAset.setGeometry(QtCore.QRect(50, 20, 151, 21))
        self.textEdit_RAset.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_RAset.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_RAset.setAcceptRichText(False)
        self.textEdit_RAset.setObjectName(_fromUtf8("textEdit_RAset"))
        self.textEdit_DECset = QtGui.QTextEdit(self.frame_Manual)
        self.textEdit_DECset.setGeometry(QtCore.QRect(50, 40, 151, 21))
        self.textEdit_DECset.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_DECset.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_DECset.setAcceptRichText(False)
        self.textEdit_DECset.setObjectName(_fromUtf8("textEdit_DECset"))
        self.label_Man_dDEC = QtGui.QLabel(self.frame_Manual)
        self.label_Man_dDEC.setGeometry(QtCore.QRect(10, 80, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Man_dDEC.setFont(font)
        self.label_Man_dDEC.setObjectName(_fromUtf8("label_Man_dDEC"))
        self.textEdit_RAOffset = QtGui.QTextEdit(self.frame_Manual)
        self.textEdit_RAOffset.setGeometry(QtCore.QRect(50, 60, 151, 21))
        self.textEdit_RAOffset.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_RAOffset.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_RAOffset.setAcceptRichText(False)
        self.textEdit_RAOffset.setObjectName(_fromUtf8("textEdit_RAOffset"))
        self.radioButton_Equ = QtGui.QRadioButton(self.frame_Manual)
        self.radioButton_Equ.setGeometry(QtCore.QRect(10, 170, 106, 20))
        self.radioButton_Equ.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_Equ.setChecked(True)
        self.radioButton_Equ.setObjectName(_fromUtf8("radioButton_Equ"))
        self.radioButton_Hor = QtGui.QRadioButton(self.frame_Manual)
        self.radioButton_Hor.setGeometry(QtCore.QRect(230, 170, 106, 20))
        self.radioButton_Hor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_Hor.setObjectName(_fromUtf8("radioButton_Hor"))
        self.textEdit_AZset = QtGui.QTextEdit(self.frame_Manual)
        self.textEdit_AZset.setGeometry(QtCore.QRect(240, 20, 131, 21))
        self.textEdit_AZset.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_AZset.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_AZset.setAcceptRichText(False)
        self.textEdit_AZset.setObjectName(_fromUtf8("textEdit_AZset"))
        self.label_Man_EL = QtGui.QLabel(self.frame_Manual)
        self.label_Man_EL.setGeometry(QtCore.QRect(210, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Man_EL.setFont(font)
        self.label_Man_EL.setObjectName(_fromUtf8("label_Man_EL"))
        self.label_Man_AZ = QtGui.QLabel(self.frame_Manual)
        self.label_Man_AZ.setGeometry(QtCore.QRect(210, 20, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Man_AZ.setFont(font)
        self.label_Man_AZ.setObjectName(_fromUtf8("label_Man_AZ"))
        self.textEdit_ELset = QtGui.QTextEdit(self.frame_Manual)
        self.textEdit_ELset.setGeometry(QtCore.QRect(240, 40, 131, 21))
        self.textEdit_ELset.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_ELset.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_ELset.setAcceptRichText(False)
        self.textEdit_ELset.setObjectName(_fromUtf8("textEdit_ELset"))
        self.label_Man_dRA = QtGui.QLabel(self.frame_Manual)
        self.label_Man_dRA.setGeometry(QtCore.QRect(10, 60, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Man_dRA.setFont(font)
        self.label_Man_dRA.setObjectName(_fromUtf8("label_Man_dRA"))
        self.textEdit_DECOffset = QtGui.QTextEdit(self.frame_Manual)
        self.textEdit_DECOffset.setGeometry(QtCore.QRect(50, 80, 151, 21))
        self.textEdit_DECOffset.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_DECOffset.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_DECOffset.setAcceptRichText(False)
        self.textEdit_DECOffset.setObjectName(_fromUtf8("textEdit_DECOffset"))
        self.graphicsView_Sky = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_Sky.setGeometry(QtCore.QRect(10, 370, 381, 311))
        self.graphicsView_Sky.setObjectName(_fromUtf8("graphicsView_Sky"))
        self.textEdit_Log = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_Log.setGeometry(QtCore.QRect(400, 380, 531, 91))
        self.textEdit_Log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_Log.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_Log.setObjectName(_fromUtf8("textEdit_Log"))
        self.label_LST_title = QtGui.QLabel(self.centralwidget)
        self.label_LST_title.setGeometry(QtCore.QRect(90, 80, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_LST_title.setFont(font)
        self.label_LST_title.setObjectName(_fromUtf8("label_LST_title"))
        self.label_LST = QtGui.QLabel(self.centralwidget)
        self.label_LST.setGeometry(QtCore.QRect(130, 80, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_LST.setFont(font)
        self.label_LST.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);"))
        self.label_LST.setObjectName(_fromUtf8("label_LST"))
        self.label_UTC_title = QtGui.QLabel(self.centralwidget)
        self.label_UTC_title.setGeometry(QtCore.QRect(90, 20, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_UTC_title.setFont(font)
        self.label_UTC_title.setObjectName(_fromUtf8("label_UTC_title"))
        self.label_UTC = QtGui.QLabel(self.centralwidget)
        self.label_UTC.setGeometry(QtCore.QRect(130, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_UTC.setFont(font)
        self.label_UTC.setStyleSheet(_fromUtf8("color: rgb(0, 255, 0);\n"
"background-color: rgb(0, 0, 0);"))
        self.label_UTC.setObjectName(_fromUtf8("label_UTC"))
        self.label_AZ_title = QtGui.QLabel(self.centralwidget)
        self.label_AZ_title.setGeometry(QtCore.QRect(330, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_AZ_title.setFont(font)
        self.label_AZ_title.setObjectName(_fromUtf8("label_AZ_title"))
        self.label_EL_title = QtGui.QLabel(self.centralwidget)
        self.label_EL_title.setGeometry(QtCore.QRect(430, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_EL_title.setFont(font)
        self.label_EL_title.setObjectName(_fromUtf8("label_EL_title"))
        self.label_AZ = QtGui.QLabel(self.centralwidget)
        self.label_AZ.setGeometry(QtCore.QRect(330, 30, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_AZ.setFont(font)
        self.label_AZ.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"background-color: rgb(0, 0, 127);"))
        self.label_AZ.setObjectName(_fromUtf8("label_AZ"))
        self.label_EL = QtGui.QLabel(self.centralwidget)
        self.label_EL.setGeometry(QtCore.QRect(430, 30, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_EL.setFont(font)
        self.label_EL.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_EL.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 0);"))
        self.label_EL.setObjectName(_fromUtf8("label_EL"))
        self.graphicsView_Cablewrap = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_Cablewrap.setGeometry(QtCore.QRect(520, 10, 111, 101))
        self.graphicsView_Cablewrap.setObjectName(_fromUtf8("graphicsView_Cablewrap"))
        self.label_Observer = QtGui.QLabel(self.centralwidget)
        self.label_Observer.setGeometry(QtCore.QRect(150, 110, 63, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Observer.setFont(font)
        self.label_Observer.setObjectName(_fromUtf8("label_Observer"))
        self.label_Obs_title = QtGui.QLabel(self.centralwidget)
        self.label_Obs_title.setGeometry(QtCore.QRect(90, 110, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Obs_title.setFont(font)
        self.label_Obs_title.setObjectName(_fromUtf8("label_Obs_title"))
        self.label_Log = QtGui.QLabel(self.centralwidget)
        self.label_Log.setGeometry(QtCore.QRect(670, 370, 21, 16))
        self.label_Log.setObjectName(_fromUtf8("label_Log"))
        self.label_Sky = QtGui.QLabel(self.centralwidget)
        self.label_Sky.setGeometry(QtCore.QRect(180, 360, 21, 16))
        self.label_Sky.setObjectName(_fromUtf8("label_Sky"))
        self.checkBox_useschedule = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_useschedule.setGeometry(QtCore.QRect(400, 110, 85, 20))
        self.checkBox_useschedule.setChecked(True)
        self.checkBox_useschedule.setObjectName(_fromUtf8("checkBox_useschedule"))
        self.label_MJD = QtGui.QLabel(self.centralwidget)
        self.label_MJD.setGeometry(QtCore.QRect(130, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_MJD.setFont(font)
        self.label_MJD.setStyleSheet(_fromUtf8("color: rgb(0, 255, 0);\n"
"background-color: rgb(0, 0, 0);"))
        self.label_MJD.setObjectName(_fromUtf8("label_MJD"))
        self.label_MJD_title = QtGui.QLabel(self.centralwidget)
        self.label_MJD_title.setGeometry(QtCore.QRect(90, 50, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_MJD_title.setFont(font)
        self.label_MJD_title.setObjectName(_fromUtf8("label_MJD_title"))
        self.label_RLST_title = QtGui.QLabel(self.centralwidget)
        self.label_RLST_title.setGeometry(QtCore.QRect(670, 10, 71, 16))
        self.label_RLST_title.setObjectName(_fromUtf8("label_RLST_title"))
        self.label_SLST_title = QtGui.QLabel(self.centralwidget)
        self.label_SLST_title.setGeometry(QtCore.QRect(810, 10, 71, 16))
        self.label_SLST_title.setObjectName(_fromUtf8("label_SLST_title"))
        self.label_RRemains = QtGui.QLabel(self.centralwidget)
        self.label_RRemains.setGeometry(QtCore.QRect(670, 80, 81, 21))
        self.label_RRemains.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_RRemains.setStyleSheet(_fromUtf8("color: rgb(0, 255, 0);\n"
"background-color: rgb(0, 0, 0);"))
        self.label_RRemains.setObjectName(_fromUtf8("label_RRemains"))
        self.label_SRemains = QtGui.QLabel(self.centralwidget)
        self.label_SRemains.setGeometry(QtCore.QRect(810, 80, 81, 21))
        self.label_SRemains.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 0, 0);"))
        self.label_SRemains.setObjectName(_fromUtf8("label_SRemains"))
        self.label_RLST = QtGui.QLabel(self.centralwidget)
        self.label_RLST.setGeometry(QtCore.QRect(670, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_RLST.setFont(font)
        self.label_RLST.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0);\n"
"background-color: rgb(0, 0, 127);"))
        self.label_RLST.setObjectName(_fromUtf8("label_RLST"))
        self.label_SLST = QtGui.QLabel(self.centralwidget)
        self.label_SLST.setGeometry(QtCore.QRect(810, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_SLST.setFont(font)
        self.label_SLST.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_SLST.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 0);"))
        self.label_SLST.setObjectName(_fromUtf8("label_SLST"))
        self.label_RRemains_title = QtGui.QLabel(self.centralwidget)
        self.label_RRemains_title.setGeometry(QtCore.QRect(670, 60, 91, 21))
        self.label_RRemains_title.setObjectName(_fromUtf8("label_RRemains_title"))
        self.label_SRemains_title = QtGui.QLabel(self.centralwidget)
        self.label_SRemains_title.setGeometry(QtCore.QRect(810, 60, 91, 21))
        self.label_SRemains_title.setObjectName(_fromUtf8("label_SRemains_title"))
        self.textBrowser_CurrentPos = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser_CurrentPos.setGeometry(QtCore.QRect(330, 80, 171, 31))
        self.textBrowser_CurrentPos.setStyleSheet(_fromUtf8("background-color: rgb(153, 102, 51);\n"
"color: rgb(0, 0, 0);"))
        self.textBrowser_CurrentPos.setObjectName(_fromUtf8("textBrowser_CurrentPos"))
        self.label_CurrentPos_title = QtGui.QLabel(self.centralwidget)
        self.label_CurrentPos_title.setGeometry(QtCore.QRect(330, 60, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_CurrentPos_title.setFont(font)
        self.label_CurrentPos_title.setObjectName(_fromUtf8("label_CurrentPos_title"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Schedule = QtGui.QAction(MainWindow)
        self.actionLoad_Schedule.setObjectName(_fromUtf8("actionLoad_Schedule"))
        self.actionOpen_Log_file = QtGui.QAction(MainWindow)
        self.actionOpen_Log_file.setObjectName(_fromUtf8("actionOpen_Log_file"))
        self.actionLoad_Config_file = QtGui.QAction(MainWindow)
        self.actionLoad_Config_file.setObjectName(_fromUtf8("actionLoad_Config_file"))
        self.menuFile.addAction(self.actionLoad_Schedule)
        self.menuFile.addAction(self.actionOpen_Log_file)
        self.menuFile.addAction(self.actionLoad_Config_file)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Telescope Control System", None))
        self.toolButton_Stop.setText(_translate("MainWindow", "STOP", None))
        self.toolButton_Start.setText(_translate("MainWindow", "Start", None))
        self.checkBox_Telescope.setText(_translate("MainWindow", "Telescope", None))
        self.checkBox_Backend.setText(_translate("MainWindow", "Backend", None))
        self.label_Communication.setText(_translate("MainWindow", "Communication", None))
        self.label_Mannual.setText(_translate("MainWindow", "Manual", None))
        self.label_Man_RA.setText(_translate("MainWindow", "RA", None))
        self.label_Man_DEC.setText(_translate("MainWindow", "DEC", None))
        self.label_Man_dDEC.setText(_translate("MainWindow", "dDEC", None))
        self.radioButton_Equ.setText(_translate("MainWindow", "Use RA-DEC", None))
        self.radioButton_Hor.setText(_translate("MainWindow", "Use AZ-EL", None))
        self.label_Man_EL.setText(_translate("MainWindow", "EL", None))
        self.label_Man_AZ.setText(_translate("MainWindow", "AZ", None))
        self.label_Man_dRA.setText(_translate("MainWindow", "dRA", None))
        self.label_LST_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">LST</span></p></body></html>", None))
        self.label_LST.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\"> 00:00:00</span></p></body></html>", None))
        self.label_UTC_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">UTC</span></p></body></html>", None))
        self.label_UTC.setText(_translate("MainWindow", "<html><head/><body><p>   2000/01/01 12:00:00</p></body></html>", None))
        self.label_AZ_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Azimuth</span></p></body></html>", None))
        self.label_EL_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Elevation</span></p></body></html>", None))
        self.label_AZ.setText(_translate("MainWindow", "00", None))
        self.label_EL.setText(_translate("MainWindow", "00", None))
        self.label_Observer.setText(_translate("MainWindow", "Raymond", None))
        self.label_Obs_title.setText(_translate("MainWindow", "Observer:", None))
        self.label_Log.setText(_translate("MainWindow", "Log", None))
        self.label_Sky.setText(_translate("MainWindow", "Sky", None))
        self.checkBox_useschedule.setText(_translate("MainWindow", "Schedule", None))
        self.label_MJD.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">  51544.5</span></p></body></html>", None))
        self.label_MJD_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">MJD</span></p></body></html>", None))
        self.label_RLST_title.setText(_translate("MainWindow", "Rising LST", None))
        self.label_SLST_title.setText(_translate("MainWindow", "Setting LST", None))
        self.label_RRemains.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">00:00:00</span></p></body></html>", None))
        self.label_SRemains.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">00:00:00</span></p></body></html>", None))
        self.label_RLST.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">00:00:00</span></p></body></html>", None))
        self.label_SLST.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">00:00:00</span></p></body></html>", None))
        self.label_RRemains_title.setText(_translate("MainWindow", "Time Remains", None))
        self.label_SRemains_title.setText(_translate("MainWindow", "Time Remains", None))
        self.textBrowser_CurrentPos.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:13pt;\">Over the horizon.</span></p></body></html>", None))
        self.label_CurrentPos_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:13pt;\">Current Position:</span></p></body></html>", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.actionLoad_Schedule.setText(_translate("MainWindow", "Load Schedule", None))
        self.actionOpen_Log_file.setText(_translate("MainWindow", "Open log file", None))
        self.actionLoad_Config_file.setText(_translate("MainWindow", "Load config file", None))

